namespace ClaudeUsageTray;

/// <summary>
/// A hundred fake proverbs for the Telegram /cita-del-dia command — meant
/// to sound wise for about half a second before falling apart. Spanish
/// only: the wordplay leans on real refranes, so a translation would just
/// be a different, worse joke.
/// </summary>
internal static class DailyQuotes
{
    public static readonly string[] All =
    {
        "A quien buen árbol se arrima, está muy cerca de un árbol",
        "Dame pan y chorizo y llámame tonto",
        "No hay mal que por un gilipollas no venga",
        "A quien madruga, ojeras crece",
        "Token token tokens y más tokens",
        "NECESITO TOKENS HIJO DE PUTA",
        "Comando no reconocido, procedo a formatear tu PC",
        "Más vale pájaro en mano que ciento en tu currículum",
        "El que no llora, no mama, pero tampoco molesta",
        "Cría cuervos y te sacarán una foto rara",
        "En boca cerrada no entran moscas, pero tampoco croquetas",
        "Perro ladrador, poco mordedor, mucho vecino cabreado",
        "No por mucho madrugar amanece más rico",
        "El hábito no hace al monje, pero ahorra en tintorería",
        "Camarón que se duerme, se convierte en gamba",
        "Quien mucho abarca, poco aprieta, pero presume mucho",
        "Al mal tiempo, otro mal tiempo",
        "Más vale tarde que en bucle infinito",
        "Ojos que no ven, corazón que tampoco procesa",
        "Donde hay patrón, no manda marinero, manda WhatsApp",
        "A caballo regalado, le miras los dientes y luego lo devuelves",
        "El que a buen árbol se arrima, luego no sabe volver a casa",
        "Zapatero, a tus zapatos, y deja mi vida en paz",
        "No hay peor sordo que el que tiene los cascos puestos",
        "Más sabe el diablo por viejo que por el tutorial de YouTube",
        "Quien siembra vientos, recoge notificaciones",
        "El que ríe último, no ha entendido el chiste todavía",
        "A buen entendedor, pocas palabras, muchas capturas de pantalla",
        "Dime con quién andas y te mandaré una solicitud de amistad",
        "No dejes para mañana lo que puedas posponer indefinidamente",
        "Más vale prevenir que tener que explicar por qué no preveniste",
        "La avaricia rompe el saco, pero el saco ya estaba roto",
        "En casa del herrero, cuchillo de Amazon",
        "Quien tiene un amigo, tiene un moroso",
        "No todo el monte es orégano, la mayoría es maleza sin identificar",
        "El que a hierro mata, luego tiene que rellenar mucho papeleo",
        "Agua que no has de beber, déjala correr y paga la factura",
        "Más vale maña que fuerza, y más vale wifi que ambas",
        "A palabras necias, oídos que igualmente están escuchando",
        "Cada oveja con su pareja, cada router con sus problemas",
        "El tiempo cura todas las heridas menos el wifi lento",
        "Quien no arriesga, no gana, pero duerme mejor",
        "A rey muerto, rey puesto, y a router muerto, otro router",
        "No es oro todo lo que reluce, a veces es solo purpurina",
        "El que espera, desespera, y el que no espera, se queda sin sitio",
        "Mucho ruido y pocas nueces, básicamente mi vecino",
        "Barriga llena, corazón contento, mente completamente apagada",
        "Genio y figura hasta que llega la factura de la luz",
        "A lo hecho, pecho, y al pecho, camiseta",
        "El que tiene tienda, que la atienda, o que contrate a alguien",
        "No hay atajo sin trabajo, excepto los atajos de teclado",
        "Cuando el río suena, es que alguien dejó el grifo abierto",
        "Al que madruga, Dios le ayuda a llegar tarde a otra cosa",
        "Más vale solo que mal acompañado, pero peor solo sin wifi",
        "El que la sigue, la consigue, o la bloquea por acoso",
        "No hay dos sin tres, ni WhatsApp sin doble check azul",
        "A falta de pan, buenas son las tostadas, pero siguen sin ser pan",
        "Quien bien te quiere, te hará esperar",
        "El que da pan a perro ajeno, pierde el pan y el perro le ignora igual",
        "Nunca llueve a gusto de nadie, y menos si dejaste la ventana abierta",
        "No hay rosa sin espinas, ni oferta sin letra pequeña",
        "Al buen callar llaman Sancho, al mal callar lo llaman ghosting",
        "Quien fue a Sevilla perdió su silla y ahora trabaja desde el suelo",
        "Piensa mal y acertarás, piensa bien y acertarás también, la verdad da igual",
        "No se ganó Zamora en una hora, se ganó en tres, que tampoco es tanto",
        "El que no arriesga, no gana, pero tampoco pierde, así que empate técnico",
        "A grandes males, grandes memes",
        "El que tiene boca se equivoca, y el que no tiene boca, también, de otra forma",
        "Ande yo caliente y ríase la gente, total ya se reían antes",
        "Quien no llora no mama, pero el que llora mucho, molesta en el cine",
        "Más vale un mal arreglo que un buen pleito, y más vale ninguno de los dos",
        "El que mucho promete, poco cumple, y el que promete poco, cumple aún menos",
        "A la tercera va la vencida, a la cuarta ya te rindes",
        "Antes se coge al mentiroso que al cojo, pero el cojo tiene ventaja moral",
        "Cuando una puerta se cierra, revisa si tienes las llaves",
        "El saber no ocupa lugar, pero sí ocupa tiempo que podrías usar durmiendo",
        "Más vale una imagen que mil palabras, salvo si la imagen está borrosa",
        "No hay peor ciego que el que no quiere ver las notificaciones",
        "Cuentas claras, amistades largas, wifi compartido, amistades cortas",
        "El que a buen puerto llega, seguramente cogió otro barco",
        "Nadie es profeta en su tierra, pero todos son expertos en Twitter",
        "A quien no le gusta el caldo, se le dan cuatro apps de delivery",
        "Vivir para ver, o simplemente ver Netflix mientras se vive",
        "Todo pasa y todo queda, sobre todo el historial de búsqueda",
        "En tierra de ciegos, el tuerto usa gafas de sol para disimular",
        "Quien tiene salud, tiene de todo, y el que no, tiene seguro médico",
        "Contigo pan y cebolla, y a los dos días indigestión",
        "El que espera lo mucho, espera lo mismo que el que espera poco, espera",
        "Más vale bueno conocido que malo por conocer, dice el que nunca sale de casa",
        "Gato con guantes no caza ratones, pero tiene mejor estilo",
        "Del dicho al hecho hay un buen trecho, y wifi por el camino",
        "No dejes camino por vereda ni vereda por atajo del GPS",
        "Éramos pocos y parió la abuela, y encima pidió que la ayudáramos con la mudanza",
        "Sistema no responde, sistema tiene razones que la razón no entiende",
        "Reiniciando sabiduría, por favor no apague el equipo",
        "Cargando consejo útil, error 404, consejo no encontrado",
        "Actualización disponible: instala paciencia, requiere reinicio",
        "Este mensaje se autodestruirá si dejas de creer en él",
        "La sabiduría ancestral dice que apagues y enciendas de nuevo",
        "Confirma que eres humano resolviendo este acertijo sin sentido",
    };
}
